apiVersion: v1
kind: Namespace
metadata:
  name: articdbm-bigdata
  labels:
    app.kubernetes.io/name: articdbm
    app.kubernetes.io/component: bigdata
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
